dataSource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/videorental
  username: postgres
  password: ada

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  hbm2dll:
    auto: none
    show_sql: false
    format_sql: false